
title: My Resume
url: 'http://junlulocky.com'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Wendy Ulacio  ## put your name
title: 'Ingeniero Civil'  ## your title
location: Montevideo, UY


## Social Profiles
# facebook: http://www.facebook.com  ## your facebook account url
twitter: https://twitter.com/wendyulacio  ## your twitter account url
linkedin: https://www.linkedin.com/in/ingwendyulacio/  ## your linkedin account url
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
